-- ============================================================
-- DATOS DE PRUEBA PARA SISTEMA DE RIEGO
-- ============================================================
-- Ejecuta esto en phpMyAdmin para insertar datos de prueba
-- y verificar que la pagina web los muestra correctamente.

USE greenhouse;

-- ============================================================
-- 1. Crear tablas si no existen
-- ============================================================

CREATE TABLE IF NOT EXISTS riego_temp_suelo (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  temperatura_suelo FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS riego_temp_ambiente (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  temperatura_ambiente FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS riego_hum_ambiente (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  humedad_ambiente FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS riego_hum_suelo (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  humedad_suelo FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS riego_potasio (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  potasio FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS riego_fosforo (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  fosforo FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS riego_nitrogeno (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nitrogeno FLOAT NOT NULL,
  fecha_lectura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. Insertar datos de prueba (30 registros cada uno)
-- ============================================================

INSERT INTO riego_temp_suelo (temperatura_suelo, fecha_lectura) VALUES
(18.5, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(19.2, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(20.1, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(21.3, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(22.0, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(21.5, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(20.8, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(19.9, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(19.0, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(18.6, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(19.5, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(20.8, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(21.8, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(22.5, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(23.0, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(22.4, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(21.6, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(20.5, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(19.8, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(19.2, DATE_SUB(NOW(), INTERVAL 5 SECOND));

INSERT INTO riego_temp_ambiente (temperatura_ambiente, fecha_lectura) VALUES
(23.5, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(24.1, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(24.8, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(25.5, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(26.2, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(25.8, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(25.0, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(24.3, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(23.8, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(23.4, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(24.0, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(24.9, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(25.8, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(26.5, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(27.0, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(26.6, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(25.8, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(24.9, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(24.2, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(23.7, DATE_SUB(NOW(), INTERVAL 5 SECOND));

INSERT INTO riego_hum_ambiente (humedad_ambiente, fecha_lectura) VALUES
(60, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(62, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(65, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(68, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(70, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(72, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(69, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(66, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(63, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(61, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(64, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(67, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(70, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(73, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(75, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(72, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(69, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(66, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(63, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(61, DATE_SUB(NOW(), INTERVAL 5 SECOND));

INSERT INTO riego_hum_suelo (humedad_suelo, fecha_lectura) VALUES
(45, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(47, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(50, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(52, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(55, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(53, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(51, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(48, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(46, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(44, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(47, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(50, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(53, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(56, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(58, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(55, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(52, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(49, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(46, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(44, DATE_SUB(NOW(), INTERVAL 5 SECOND));

INSERT INTO riego_potasio (potasio, fecha_lectura) VALUES
(120, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(125, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(130, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(128, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(135, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(140, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(138, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(132, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(127, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(122, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(128, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(134, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(139, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(142, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(145, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(140, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(136, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(130, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(126, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(123, DATE_SUB(NOW(), INTERVAL 5 SECOND));

INSERT INTO riego_fosforo (fosforo, fecha_lectura) VALUES
(15, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(16, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(17, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(16, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(18, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(19, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(18, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(17, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(16, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(15, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(16, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(17, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(19, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(20, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(21, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(19, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(18, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(17, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(16, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(16, DATE_SUB(NOW(), INTERVAL 5 SECOND));

INSERT INTO riego_nitrogeno (nitrogeno, fecha_lectura) VALUES
(80, DATE_SUB(NOW(), INTERVAL 145 SECOND)),
(82, DATE_SUB(NOW(), INTERVAL 135 SECOND)),
(85, DATE_SUB(NOW(), INTERVAL 125 SECOND)),
(83, DATE_SUB(NOW(), INTERVAL 115 SECOND)),
(88, DATE_SUB(NOW(), INTERVAL 105 SECOND)),
(90, DATE_SUB(NOW(), INTERVAL 95 SECOND)),
(87, DATE_SUB(NOW(), INTERVAL 85 SECOND)),
(84, DATE_SUB(NOW(), INTERVAL 75 SECOND)),
(81, DATE_SUB(NOW(), INTERVAL 65 SECOND)),
(79, DATE_SUB(NOW(), INTERVAL 55 SECOND)),
(83, DATE_SUB(NOW(), INTERVAL 50 SECOND)),
(87, DATE_SUB(NOW(), INTERVAL 45 SECOND)),
(91, DATE_SUB(NOW(), INTERVAL 40 SECOND)),
(93, DATE_SUB(NOW(), INTERVAL 35 SECOND)),
(95, DATE_SUB(NOW(), INTERVAL 30 SECOND)),
(91, DATE_SUB(NOW(), INTERVAL 25 SECOND)),
(88, DATE_SUB(NOW(), INTERVAL 20 SECOND)),
(84, DATE_SUB(NOW(), INTERVAL 15 SECOND)),
(81, DATE_SUB(NOW(), INTERVAL 10 SECOND)),
(79, DATE_SUB(NOW(), INTERVAL 5 SECOND));
